# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        key: ${{ secrets.VM_SSH }}
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USERNAME }}
        script: |
          # pm2 delete all
          sudo pkill -9 node
          cd /home/azureuser/lightspeed-AI-Challenge
          git pull
          npm install
          # pm2 start npm --start
          npm start

# name: Node.js CI/CD with SSH Deployment

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3
      
#     - name: Setup Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: 18

#     - name: Install dependencies
#       run: npm install
      
#     - name: Build
#       run: npm run build --if-present

#     - name: Deploy to VM
#       uses: appleboy/ssh-action@v1.0.0
#       with:
#         host: ${{ secrets.VM_IP }}
#         username: ${{ secrets.VM_USERNAME }}
#         key: ${{ secrets.VM_SSH }}
#         script: |
#           node -v
#           npm -v
#           cd /home/azureuser/lightspeed-AI-Challenge
#           ls
#           git pull origin main
#           npm install
#           sudo node app.js
